---
swagger: "2.0"
info:
  description: This is the API documentation for the COP 4331 Contact Manager app (Group 24)
  version: 1.0.0
  title: Contact Manager
  contact:
    email: ch715804@ucf.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: cop4331-group24.online
basePath: /LAMPAPI
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /Login.php:
    post:
      tags:
      - Users
      summary: Logs in to contact manager app
      description: Logs in to contact manager app
      operationId: doLogin
      consumes:
      - application/json
      parameters:
      - in: body
        name: loginItem
        description: Login
        required: false
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
  /Register.php:
    post:
      tags:
      - Users
      summary: Registers user
      description: Registers user into contact manager app
      operationId: doRegister
      consumes:
      - application/json
      parameters:
      - in: body
        name: registerItem
        description: Register
        required: false
        schema:
          $ref: '#/definitions/Register'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
  /AddContact.php:
    post:
      tags:
      - Contacts
      summary: Creates a new contact
      description: Adds a new contact
      operationId: addContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: addContactItem
        description: Adds a contact
        required: false
        schema:
          $ref: '#/definitions/AddContact'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
  /SearchContact.php:
    get:
      tags:
      - Contacts
      summary: Searches for a contact in your contacts list
      description: Searches for a contact.
      operationId: searchContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: searchContactItem
        description: "Searches for a contact. (For the value of \"data\", use \"1\" to search by first name, \"2\" for last name, \"3\" for phone, \"4\" for email. Depending on the value of \"data\", choose the value of \"value\" appropriately.)"
        required: false
        schema:
          $ref: '#/definitions/SearchContact'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
  /UpdateContact.php:
    post:
      tags:
      - Contacts
      summary: Updates contact info
      description: Updates information of an existing contact
      operationId: updateContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: updateContactItem
        description: Update existing contact info. ("id" should be the id value of the contact)
        required: false
        schema:
          $ref: '#/definitions/UpdateContact'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
  /DeleteContact.php:
    post:
      tags:
      - Contacts
      summary: Delete a contact
      description: Deletes a contact
      operationId: deleteContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: deleteContactItem
        description: Deletes a contact. ("id" should be the id value of the contact)
        required: false
        schema:
          $ref: '#/definitions/DeleteContact'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
        "500":
          description: Server Error
definitions:
  Login:
    type: object
    required:
    - login
    - password
    properties:
      login:
        type: string
        example: fred
      password:
        type: string
        example: secret
  Register:
    type: object
    required:
    - password
    properties:
      first:
        type: string
        example: fred
      last:
        type: string
        example: van fleet
      login:
        type: string
        example: fvf
      password:
        type: string
        example: secret
  AddContact:
    type: object
    required:
    - email
    - userID
    properties:
      first:
        type: string
        example: Joe
      last:
        type: string
        example: Burrow
      phone:
        type: string
        example: 123 456 7890
      email:
        type: string
        example: jb@gmail.com
      userID:
        type: string
        example: "5"
  SearchContact:
    type: object
    required:
    - data
    - userID
    - value
    properties:
      value:
        type: string
        example: Joe
      userID:
        type: string
        example: "5"
      data:
        type: string
        example: "1"
  UpdateContact:
    type: object
    required:
    - email
    - first
    - id
    - last
    - phone
    properties:
      first:
        type: string
        example: Joe
      last:
        type: string
        example: Butler
      phone:
        type: string
        example: 123 768 9901
      email:
        type: string
        example: jb@gmail.com
      id:
        type: string
        example: "22"
  DeleteContact:
    type: object
    required:
    - id
    properties:
      id:
        type: string
        example: "22"
